ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'PRINTER';
ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'MATERIAL_SYSTEM';
ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'BUILD_PLATE';
ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'HOTEND';
ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'SAFETY';
ALTER TYPE "ImportEntityType" ADD VALUE IF NOT EXISTS 'SMART_PLUG';
